import pycinema
import pycinema.filters
import pycinema.theater
import pycinema.theater.views

# pycinema settings
PYCINEMA = { 'VERSION' : '2.1.0'}

# filters
TableView_0 = pycinema.filters.TableView()
CinemaDatabaseReader_0 = pycinema.filters.CinemaDatabaseReader()
ParallelCoordinates_0 = pycinema.filters.ParallelCoordinates()
TableQuery_0 = pycinema.filters.TableQuery()
ImageReader_0 = pycinema.filters.ImageReader()
ImageView_0 = pycinema.filters.ImageView()
ColorMapping_0 = pycinema.filters.ColorMapping()
TextView_0 = pycinema.filters.TextView()
ImageView_1 = pycinema.filters.ImageView()
DepthCompositing_0 = pycinema.filters.DepthCompositing()

# properties
TableView_0.inputs.table.set(ParallelCoordinates_0.outputs.table, False)
TableView_0.inputs.selection.set([3], False)
CinemaDatabaseReader_0.inputs.path.set("/home/jones/projects/cinema-lib/pycinema/data/ScalarImages.cdb/", False)
CinemaDatabaseReader_0.inputs.file_column.set("FILE", False)
ParallelCoordinates_0.inputs.table.set(TableQuery_0.outputs.table, False)
ParallelCoordinates_0.inputs.ignore.set(['^file', '^id'], False)
ParallelCoordinates_0.inputs.state.set({'time': {'C': False, 'O': ['0.0', '0.25', '0.5', '0.75', '1.0'], 'V': [0, 1, 2, 3, 4], 'M': 'S'}, 'phi': {'C': False, 'O': ['0.0', '45.0', '90.0', '135.0', '180.0', '225.0', '270.0', '315.0'], 'V': [2, 3, 4, 5], 'M': 'S'}, 'theta': {'C': False, 'O': ['20.0'], 'V': [0], 'M': 'S'}, 'object_id': {'C': True, 'O': ['s0', 's1'], 'V': [0, 1], 'M': 'S'}}, False)
TableQuery_0.inputs.table.set(CinemaDatabaseReader_0.outputs.table, False)
TableQuery_0.inputs.sql.set("SELECT * FROM input WHERE object_id in ('s0','s1') and theta=20", False)
ImageReader_0.inputs.table.set(ParallelCoordinates_0.outputs.table, False)
ImageReader_0.inputs.file_column.set("FILE", False)
ImageReader_0.inputs.cache.set(True, False)
ImageView_0.inputs.images.set(ColorMapping_0.outputs.images, False)
ImageView_0.inputs.selection.set([1], False)
ColorMapping_0.inputs.map.set("plasma", False)
ColorMapping_0.inputs.nan.set((0.6, 0.757, 0.945, 1.0), False)
ColorMapping_0.inputs.range.set((0.0, 2.0), False)
ColorMapping_0.inputs.channel.set("y", False)
ColorMapping_0.inputs.images.set(DepthCompositing_0.outputs.images, False)
ColorMapping_0.inputs.composition_id.set(-1, False)
TextView_0.inputs.text.set("test", False)
ImageView_1.inputs.images.set(ImageView_0.outputs.images, False)
ImageView_1.inputs.selection.set([], False)
DepthCompositing_0.inputs.images_a.set(ImageReader_0.outputs.images, False)
DepthCompositing_0.inputs.images_b.set([], False)
DepthCompositing_0.inputs.depth_channel.set("depth", False)
DepthCompositing_0.inputs.compose.set(ParallelCoordinates_0.outputs.compose, False)

# layout
tabFrame1 = pycinema.theater.TabFrame()
splitFrame1 = pycinema.theater.SplitFrame()
splitFrame1.setHorizontalOrientation()
splitFrame2 = pycinema.theater.SplitFrame()
splitFrame2.setVerticalOrientation()
view1 = pycinema.theater.views.NodeEditorView()
splitFrame2.insertView( 0, view1 )
splitFrame6 = pycinema.theater.SplitFrame()
splitFrame6.setHorizontalOrientation()
view10 = pycinema.theater.views.FilterView( ImageView_1 )
splitFrame6.insertView( 0, view10 )
view12 = pycinema.theater.views.FilterView( ColorMapping_0 )
splitFrame6.insertView( 1, view12 )
splitFrame6.setSizes([1276, 1276])
splitFrame2.insertView( 1, splitFrame6 )
splitFrame2.setSizes([667, 667])
splitFrame1.insertView( 0, splitFrame2 )
splitFrame3 = pycinema.theater.SplitFrame()
splitFrame3.setVerticalOrientation()
view4 = pycinema.theater.views.FilterView( ParallelCoordinates_0 )
splitFrame3.insertView( 0, view4 )
view5 = pycinema.theater.views.FilterView( ImageView_0 )
splitFrame3.insertView( 1, view5 )
splitFrame3.setSizes([616, 718])
splitFrame1.insertView( 1, splitFrame3 )
splitFrame1.setSizes([2556, 2556])
tabFrame1.insertTab(0, splitFrame1)
tabFrame1.setTabText(0, 'Layout 1')
splitFrame4 = pycinema.theater.SplitFrame()
splitFrame4.setHorizontalOrientation()
view6 = pycinema.theater.views.NodeEditorView()
splitFrame4.insertView( 0, view6 )
splitFrame5 = pycinema.theater.SplitFrame()
splitFrame5.setVerticalOrientation()
view7 = pycinema.theater.views.FilterView( TextView_0 )
splitFrame5.insertView( 0, view7 )
view8 = pycinema.theater.views.FilterView( TextView_0 )
splitFrame5.insertView( 1, view8 )
splitFrame5.setSizes([220, 256])
splitFrame4.insertView( 1, splitFrame5 )
splitFrame4.setSizes([318, 318])
tabFrame1.insertTab(1, splitFrame4)
tabFrame1.setTabText(1, 'Layout 2')
tabFrame1.setCurrentIndex(0)
pycinema.theater.Theater.instance.setCentralWidget(tabFrame1)

# execute pipeline
TableView_0.update()
